version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      - clickhouse-config:/etc/clickhouse-server

volumes:
  clickhouse-data:
  clickhouse-logs:
  clickhouse-config:
